NAME: 'lucchi_subset2_lre4_wcrp'

MODEL:
    input_nc: 1
    output_nc: 2
    num_classes: 2
    input_channels: 64
    level: 1

TRAIN:
    resume: False
    model_name: '37000'
    consist_fea_loss: True
    threshold: 0.7
    weight_fa: 0.1
    if_valid: True
    cache_path: '../caches/'
    save_path: '/braindat/lab/yd/august/expriments/DA-ISC_0211/models/2023-02-16--12-14-10_lucchi_subset2_fa3/'
    log_path: '../logs/'
    valid_path: '../valids/'
    loss_func: 'WeightedMSELoss'   # 'WeightedBCELoss', 'BCELoss'
    if_adv_weight: False
    cross_loss_source: False
    cross_loss_target: True
    cross_aug: True
    weight_cross: 0.1
    weight_consist_fea: 0.1
    consistency_weight_rampup: True

    opt_type: 'adam'  # sgd
    lr_mode: 'fixed'
    total_iters: 200000
    rampup_iters: 50000
    learning_rate: 0.0001
    learning_rate_ms: 0.0001
    learning_rate_mt: 0.0001
    display_freq: 100
    show_freq: 500
    valid_freq: 500
    save_freq: 500
    power: 0.9
    weight_adv_temporal: 0.001
    weight_adv_spatial: 0.001
    lamda_wd: 0.001

    batch_size: 1
    num_workers: 4
    if_cuda: True

    random_seed: 555  # -1 is none

DATA:
    data_dir_img: '/braindat/lab/yd/august/expriments/DA_Mito_yindan/data/VNC3/training/'
    data_dir_label: '/braindat/lab/yd/august/expriments/DA_Mito_yindan/data/VNC3/training_groundtruth/'
    data_list: '/braindat/lab/yd/august/expriments/DA_Mito_yindan/data/VNC3/train.txt'
    input_size: 512
    source_stride: 1
    data_dir_target: '/braindat/lab/yd/august/expriments/DA_Mito_yindan/data/Lucchi/testing'
    data_dir_target_label: '/braindat/lab/yd/august/expriments/DA_Mito_yindan/data/Lucchi/testing_groundtruth'
    data_list_target: '/braindat/lab/yd/august/expriments/DA_Mito_yindan/data/Lucchi/testing.txt'
    input_size_target: 512
    target_stride: 10
    data_dir_val: '/braindat/lab/yd/august/expriments/DA_Mito_yindan/data/Lucchi/training'
    data_dir_val_label: '/braindat/lab/yd/august/expriments/DA_Mito_yindan/data/Lucchi/training_groundtruth'
    data_list_val: '/braindat/lab/yd/august/expriments/DA_Mito_yindan/data/Lucchi/train.txt'
    input_size_target: 512

TEST:
    pad: 0
    model_name: ''